services:
  - type: web
    name: bihar-swimming-association
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn swimming_federation_bihar.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.13.0