# Generated by Django 5.2.4 on 2025-07-26 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach')], max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('home_association', models.CharField(blank=True, max_length=200)),
                ('photograph', models.ImageField(upload_to='documents/photos/')),
                ('id_proof', models.FileField(upload_to='documents/id_proofs/')),
                ('dob_proof', models.FileField(upload_to='documents/dob_proofs/')),
                ('address_proof', models.FileField(upload_to='documents/address_proofs/')),
                ('coaching_certificate', models.FileField(blank=True, help_text='Required for coaches only.', null=True, upload_to='documents/coaching_certs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
